<?php

/**
 * @file
 * Contains event_brite.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\Core\Link;

/**
 * Implements hook_help().
 */
function event_brite_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the event_brite module.
    case 'help.page.event_brite':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Integration with event brite platform') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function event_brite_theme($existing, $type, $theme, $path) {
  return 
    [
      'event_brite' => [
        'render element' => 'children',
      ],
      'nextevents' => [
        'render element' => 'elements',
        'variables' => array( 'events' => array() ),
        'template' => 'block--next-events'
      ]
    ];
}

/**
 * Implementation of hook_form_alter()
 */
function event_brite_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'fancy_login_user_login_form') {
    if (\Drupal::config('user.settings')->get('register') != USER_REGISTER_ADMINISTRATORS_ONLY) {
      $url = Url::fromRoute('user.register', [], ['attributes' => ['title' => t('Registrate')]]);
      $items['create_account'] = Link::fromTextAndUrl(t('Registrate'), $url);

      $form['pass']['#weight'] = -1;
      $form['actions']['#weight'] = 0;
      $form['user_links']['#weight'] = 10;

      $form['title'] = [
        '#markup' => t('<h2 class="block-title">Ingresar</h2>'),
        '#weight' => -2,
      ];

      $form['newuser'] = [
        '#type' => 'container',
        '#weight' => 99,
        '#attributes' => [
          'class' => ['fancy_login_newuser_wrapper']
        ]
      ];

      $form['newuser']['title'] = [
        '#markup' => t('<h4 class="medium-text-center block-title margin-bottom-20">¿Eres usuario nuevo?</h4>'),
        '#weight' => 1
      ];

      $form['newuser']['links'] = [
        '#theme' => 'item_list',
        '#items' => $items,
        '#weight' => 2,
        '#attributes' => [
          'class' => ['button', 'link', 'medium-text-center', 'margin-top-20', 'margin-bottom-20']
        ]
      ];

      $form['newuser']['description'] = [
        '#markup' => t('<p class="description padding-left-50 padding-right-50 medium-text-center">Y accede a todos los servicios que ofrece COLFUTURO.</p>'),
        '#weight' => 3,
      ];
    }
  }
}
