<?php

/**
 * @file
 * Contains colfuturo_apps.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function colfuturo_apps_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the colfuturo_apps module.
    case 'help.page.colfuturo_apps':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module allow integrate apps of colfuturo with drupal session') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function colfuturo_apps_theme() {
  return [
    'colfuturo_apps' => [
      'render element' => 'children',
    ],
  ];
}
