miniorange_oauth_client.customer_setup:
  route_name: miniorange_oauth_client.customer_setup
  title: 'Customer Setup'
  weight: 10
  base_route: miniorange_oauth_client.customer_setup

miniorange_oauth_client.config_clc:
  route_name: miniorange_oauth_client.config_clc
  title: 'OAuth Client'
  weight: 20
  base_route: miniorange_oauth_client.customer_setup

miniorange_oauth_client.mapping:
  route_name: miniorange_oauth_client.mapping
  title: 'Attribute & Role Mapping'
  weight: 30
  base_route: miniorange_oauth_client.customer_setup
miniorange_oauth_client.licensing:
  route_name: miniorange_oauth_client.licensing
  title: 'Licensing'
  weight: 40
  base_route: miniorange_oauth_client.customer_setup
miniorange_oauth_client.faq:
  route_name: miniorange_oauth_client.faq
  title: 'FAQs'
  weight: 50
  base_route: miniorange_oauth_client.customer_setup
miniorange_oauth_client.support:
  route_name: miniorange_oauth_client.support
  title: 'Support'
  weight: 60
  base_route: miniorange_oauth_client.customer_setup